src/Entity/Carte.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CarteRepository")
 */
class Carte
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $circonference;

    /**
     * @ORM\Column(type="integer")
     */
    private $nb_rivieres;

    /**
     * @ORM\Column(type="integer")
     */
    private $nb_chaine_montagnes;

    /**
     * @ORM\Column(type="integer")
     */
    private $nb_forets;

    /**
     * @ORM\Column(type="integer")
     */
    private $temperature_max;

    /**
     * @ORM\Column(type="integer")
     */
    private $temperature_min;

    /**
     * @ORM\Column(type="datetime")
     */
    private $cree_le;

    /**
     * @ORM\Column(type="datetime")
     */
    private $modifiee_le;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;
	
	public function __construct()
	{
		$this->cree_le = new \DateTime();
	}
	

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCirconference(): ?int
    {
        return $this->circonference;
    }

    public function setCirconference(int $circonference): self
    {
        $this->circonference = $circonference;

        return $this;
    }

    public function getNbRivieres(): ?int
    {
        return $this->nb_rivieres;
    }

    public function setNbRivieres(int $nb_rivieres): self
    {
        $this->nb_rivieres = $nb_rivieres;

        return $this;
    }

    public function getNbChaineMontagnes(): ?int
    {
        return $this->nb_chaine_montagnes;
    }

    public function setNbChaineMontagnes(int $nb_chaine_montagnes): self
    {
        $this->nb_chaine_montagnes = $nb_chaine_montagnes;

        return $this;
    }

    public function getNbForets(): ?int
    {
        return $this->nb_forets;
    }

    public function setNbForets(int $nb_forets): self
    {
        $this->nb_forets = $nb_forets;

        return $this;
    }

    public function getTemperatureMax(): ?float
    {
        return $this->temperature_max;
    }

    public function setTemperatureMax(float $temperature_max): self
    {
        $this->temperature_max = $temperature_max;

        return $this;
    }

    public function getTemperatureMin(): ?float
    {
        return $this->temperature_min;
    }

    public function setTemperatureMin(float $temperature_min): self
    {
        $this->temperature_min = $temperature_min;

        return $this;
    }

    public function getCreeLe(): ?\DateTimeInterface
    {
        return $this->cree_le;
    }

    public function setCreeLe(\DateTimeInterface $cree_le): self
    {
        $this->cree_le = $cree_le;

        return $this;
    }

    public function getModifieeLe(): ?\DateTimeInterface
    {
        return $this->modifiee_le;
    }

    public function setModifieeLe(\DateTimeInterface $modifiee_le = null): self
    {
        $this->modifiee_le = $modifiee_le;
		if ($modifiee_le == null){
			$this->modifiee_le = new \DateTime();
		}

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }
}

src/Form/CarteType.php
<?php

namespace App\Form;

use App\Entity\Carte;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CarteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('circonference')
            ->add('nb_rivieres')
            ->add('nb_chaine_montagnes')
            ->add('nb_forets')
            ->add('temperature_max')
            ->add('temperature_min')
            ->add('nom')
            ->add('description')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Carte::class,
			'translation_domain' => 'forms',
        ]);
    }
}

src/Controller/CarteController.php
<?php

namespace App\Controller;

use App\Repository\CarteRepository;
use App\Form\CarteType;
use App\Entity\Carte;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class CarteController extends AbstractController
{
	
	/**
	 *  @var CarteRepository
	 */
	private $carte_repo;
	
	/**
	 *  @var ObjectManager
	 */
	private $em;
	
	
	public function __construct(CarteRepository $carte_repo, ObjectManager $em)
	{
		$this->carte_repo = $carte_repo;
		$this->em = $em;
	}
	
    /**
     * @Route("/carte/toutes", name="carte.index")
     */
    public function index()
    {
		$cartes = $this->carte_repo->findAll();
        return $this->render('carte/index.html.twig', [
            'controller_name' => 'CarteController',
			'cartes' => $cartes,
        ]);
    }
	
	/**
     * @Route("/carte/creation", name="carte.crud.create")
     */
	public function createCarte(Request $request)
	{
		$carte = new Carte();
		$carte->setModifieeLe();
		$form = $this->createForm(CarteType::class, $carte);
		$form->handleRequest($request);
		
		if ($form->isSubmitted() && $form->isValid()) {
			$this->em->persist($carte);
			$this->em->flush();
			$this->addFlash('success','Carte créée avec succès !');
			return $this->redirectToRoute("carte.index");
		}	
		
		return $this->render('carte/crud.html.twig', [
            'controller_name' => 'CarteController',
			'form' => $form->createView(),
        ]);
	}
	
	/**
	 *  
	 *  @param [in] $request Request
	 *  @param [in] $carte Carte
	 *  @return RedirectResponse
	 *  
	 *  @Route("/carte/suppression/{id}", name="carte.crud.delete")
	 */
	public function deleteCarte(Request $request, Carte $carte)
	{	
		if ($this->isCsrfTokenValid('delete' . $carte->getId(), $request->get('_token'))){
			$this->em->remove($carte);
			$this->em->flush();
			$this->addFlash('success','Carte supprimée avec succès !');

		}
		return $this->redirectToRoute("carte.index");

		
	}
}

templates/base.admin.html.twig
{% extends 'base.html.twig' %}


{% block body %}

<div class="container-fluid">

	<nav class="navbar navbar-expand-lg navbar-light bg-info">
	  <a class="navbar-brand" href="#">Administration</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto">
		  <li class="nav-item dropdown  {% if controller_name is defined and controller_name == "CarteController" %}active{% endif %}">
			<a class="nav-link dropdown-toggle" href="{{ path('carte.index')}}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			  Cartes
			</a>
			<div class="dropdown-menu" aria-labelledby="navbarDropdown">
			  <a class="dropdown-item" href="{{ path('carte.crud.create')}}">Créer une carte</a>
			  <a class="dropdown-item" href="{{ path('carte.index')}}">Liste des cartes</a>
			  <div class="dropdown-divider"></div>
			  <a class="dropdown-item" href="#">Something else here</a>
			</div>
		  </li>
		  <li class="nav-item">
			<a class="nav-link" href="#">Link</a>
		  </li>
		</ul>
		<form class="form-inline my-2 my-lg-0">
		  <input class="form-control mr-sm-2" type="search" placeholder="Mot-clé" aria-label="Search">
		  <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Rechercher</button>
		</form>
	  </div>
	</nav>
	
	{% block principal %}{% endblock %}
	
</div>

{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
		
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        {% block stylesheets %}{% endblock %}

    </head>
    <body>
	
        {% block body %}{% endblock %}
		
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
		{% block javascripts %}{% endblock %}
    </body>
</html>

templates/carte/crud.html.twig
{% extends 'base.admin.html.twig' %}

{% block title %}Création de carte aléatoire{% endblock %}

{% block principal %}

	<div class="container mt-4">
		<h1>Créer une nouvelle carte aléatoire</h1>
		{{ form_start(form) }}
			<div class="row">
				<div class="col-md-9">
					{{ form_row(form.nom) }}
				</div>
			</div>
			<div class="row">
				<div class="col-md-9">
					{{ form_row(form.description) }}
				</div>
			</div>
			<div class="row">
				<div class="col-md-3">
					{{ form_row(form.circonference) }}
				</div>
			</div>
			<div class="row">
				<div class="col-md-3">
					{{ form_row(form.nb_forets) }}
				</div>
				<div class="col-md-3">
					{{ form_row(form.nb_rivieres) }}
				</div>
				<div class="col-md-3">
					{{ form_row(form.nb_chaine_montagnes) }}
				</div>
			</div>
			<div class="row">
				<div class="col-md-3">
					{{ form_row(form.temperature_min) }}
				</div>
				<div class="col-md-3">
					{{ form_row(form.temperature_max) }}
				</div>
			</div>
			<div class="row  justify-content-md-end">
				<div class="col-md-3">
					<button class="btn btn-success btn-block" type="submit"> Lancer la création <i class="fas fa-magic"></i></button>
				</div>
				<div class="col-md-3">
				</div>
			</div>
		{{ form_end(form) }}
	</div>

{% endblock %}

{% block javascripts %}
<script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js" integrity="sha384-0pzryjIRos8mFBWMzSSZApWtPl/5++eIfzYmTgBBmXYdhvxPc+XcFEk+zJwDgWbP" crossorigin="anonymous"></script>
{% endblock %}

templates/carte/index.html.twig
{% extends 'base.admin.html.twig' %}

{% block title %}Hello CarteController!{% endblock %}

{% block principal %}
	
	<div class="container mt-4">
		
		{% for message in app.flashes('success') %}
			<div class="alert alert-success">{{message}}</div>
		{% endfor %}
		
		<div class="row">
			<a href="{{path('carte.crud.create')}}" class="btn btn-info"><i class="fas fa-plus-square"></i> Créer une nouvelle carte</a>
		</div>
		<div class="row mt-2">
			<table class="table table-striped table-hover">
			  <thead>
				<tr>
				  <th scope="col">#</th>
				  <th scope="col">Nom</th>
				  <th scope="col">Circonférence</th>
				  <th scope="col">Nb Rivières/Montagnes/Forêts</th>
				  <th scope="col">Température min/max</th>
				  <th scope="col" class="text-center">Visualiser</th>
				  <th scope="col" class="text-center">Supprimer</th>
				</tr>
			  </thead>
			  <tbody>
			{% for carte in cartes %}
				<tr>
					<th scope="row">{{carte.id}}</th>
					<td>{{carte.nom}}</td>
					<td>{{carte.circonference}}</td>
					<td>{{carte.nbRivieres}}/{{carte.nbChaineMontagnes}}/{{carte.nbForets}}</td>
					<td>{{carte.temperatureMin}}/{{carte.temperatureMax}}</td>
					<td class="text-center"><button class="btn btn-info" type="submit"><i class="fas fa-eye"></i></button></td>
					<td class="text-center">
						<form method="post" action="{{ path('carte.crud.delete', {id : carte.id}) }}" onSubmit="return confirm('Etes-vous certains de vouloir supprimer cette carte ?');">
							<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ carte.id) }}">
							<button class="btn btn-danger" type="submit"><i class="fas fa-trash-alt"></i></button>
						</form>
					</td>
				</tr>
			{% endfor %}
			  </tbody>
			</table>
		</div>
	</div>

{% endblock %}

{% block javascripts %}
<script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js" integrity="sha384-0pzryjIRos8mFBWMzSSZApWtPl/5++eIfzYmTgBBmXYdhvxPc+XcFEk+zJwDgWbP" crossorigin="anonymous"></script>
{% endblock %}